### ISSUE TITLE
Option to disable Google Analytics

### ISSUE THREAD

**Issue by Tekl** [marioestrada/safari-omnikey#1]
It would be nice to have a option to disable the Google Analytics tracking completely. Maybe a tracking free version would be nice.

**Comment by marioestrada** [comment]
I track some actions like adding and removing urls, and when keyword searches are used I track the domain they go to, no personally identifiable data is sent. I'll look into adding an option to completely remove this.

**Comment by fletom** [comment]
Can we also have the option to disable referral codes being added? Most users won't care either way and leave the default (on), but to some of us that code running without an option to turn it off is somewhat offensive.

**Comment by marioestrada** [comment]
@fletom the option is already there in the preferences, I hope making free open source software doesn't offend anybody specially when I have to pay $99/year to publish it.

**Comment by fletom** [comment]
@marioestrada Ah, sorry. I actually hadn't looked at the code in about a year, and I see you added that feature last July. Thanks for that.

I would argue that injecting referral codes into 3rd party sites without asking first or having an option to disable it is definitely not 100% morally sound, even in free software. But feel free to disagree, and it doesn't matter now since you've added the option already.

Thank you for making Omnikey.

**Comment by marioestrada** [comment]
No problem 😃 I do add some text explaining how the extension adds referrals in the homepage: http://marioestrada.github.io/safari-omnikey/. But since this is just a hobby project of mine it's in a very slow development pace, I basically only add feature whenever I find the free time which is not very often sadly.

**Comment by marioestrada** [comment]
Added in `1.4.0`
