### ISSUE TITLE
Version 1.5.0 not available in Safari Extensions Gallery

### ISSUE THREAD

**Issue by patrickrushton** [marioestrada/safari-omnikey#20]
The version of Omnikey installed from Safari Extensions Gallery seems to be stuck at v1.4.0 and doesn't auto-update to v1.5.0

Trying to install the v1.5.0 omnikey.safariextz manually with the Safari Extensions Gallery version already installed results in an error:

> Safari can’t install this extension
> An error occurred while installing the extension “Omnikey”.

**Comment by marioestrada** [comment]
ughh, I'll take a look

**Comment by msedlmairHH** [comment]
@patrickrushton make sure to uninstall version v.1.4.0 before manually installing v1.5.0.
Had the same error. Make sure to uninstall the old one first.

**Comment by marioestrada** [comment]
I'm resubmitting it to the Safari Extensions Gallery, but they've always been hard to work with, I had to submit it 5 different times over a year for them to post it there. My suggestion is installing it from http://marioestrada.github.io/safari-omnikey/ to avoid any possible issues.

**Comment by MartinZubek** [comment]
Any chance it would get to official Safari Extension Gallery after all? :)

**Comment by marioestrada** [comment]
I need to make some changes to the extension, it'll be updated there at some point in the near future.

**Comment by MartinZubek** [comment]
Great news, thanks. :)

**Comment by Vertux** [comment]
> > Trying to install the v1.5.0 omnikey.safariextz manually with the Safari Extensions Gallery version already installed results in an error:
> 
> Safari can’t install this extension
> An error occurred while installing the extension “Omnikey”.
> 

I have the same issue with Safari v11.0.3 (13604.5.3)

P.S.: In the extension gallery I still could find only v1.4.0, which seems to be pretty buggy, because if you try to add a new search engine, it takes the current URL as placeholder, not a big deal so far. When you overwrite it with the correct search URL and key and then try to select it as the default search for Safari, it shows you only the old wrong placeholder you had overwritten already - and the worst thing is, if you search for something the wrong URL is used, which of course goes wrong.

**Comment by marioestrada** [comment]
New version should be on Apple Extensions Gallery now.
